// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpYpdlbzO34bee80BqxIfs5wNE7q3IxGg',
    appId: '1:872823556589:web:55216b53db83f624e97fe4',
    messagingSenderId: '872823556589',
    projectId: 'carpool-958a7',
    authDomain: 'carpool-958a7.firebaseapp.com',
    storageBucket: 'carpool-958a7.appspot.com',
    measurementId: 'G-2JKFTD8SYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBREB5uHeVjK7eI5Bqm4VzifTjCmPeZT4c',
    appId: '1:872823556589:android:a2d9d6aae34f4580e97fe4',
    messagingSenderId: '872823556589',
    projectId: 'carpool-958a7',
    storageBucket: 'carpool-958a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUlnm_gtTFIxbzPGWSitRnHk9VQjc9wGs',
    appId: '1:872823556589:ios:e2fbed86ef8c67abe97fe4',
    messagingSenderId: '872823556589',
    projectId: 'carpool-958a7',
    storageBucket: 'carpool-958a7.appspot.com',
    iosClientId: '872823556589-2mj0h58geqnccpq945uhvq0ovkhjut0e.apps.googleusercontent.com',
    iosBundleId: 'com.example.carpoolingApp',
  );
}
